name: spring-boot-microservice-course

services:
  catalog-service:
    image: kenduraghav/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://catalog-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  bookstore-order-service:
    image: kenduraghav/bookstore-order-service
    container_name: bookstore-order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest 
      - RABBITMQ_PASSWORD=guest 
      - ORDERS_CATALOG_SERVICE_URL=http://bookstore-api-gateway:8989/catalog
      - DB_URL=jdbc:postgresql://order-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  notification-service:
      image: kenduraghav/notification-service
      container_name: notification-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - RABBITMQ_HOST=bookstore-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest 
        - RABBITMQ_PASSWORD=guest 
        - DB_URL=jdbc:postgresql://notifications-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - MAIL_HOST=mailhog
        - MAIL_PORT=1025
      ports:
        - "8083:8083"
      restart: unless-stopped
      depends_on:
        notifications-db:
          condition: service_healthy
        bookstore-rabbitmq:
          condition: service_healthy
        mailhog:
          condition: service_started
      deploy:
        resources:
          limits:
            memory: 700m

  bookstore-api-gateway:
      image: kenduraghav/bookstore-api-gateway
      container_name: bookstore-api-gateway
      environment:
        - SPRING_PROFILES_ACTIVE=docker        - CATALOG_SERVICE_URL=http://catalog-service:8081        - ORDER_SERVICE_URL=http://bookstore-order-service:8082
      ports:
        - "8989:8989"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 700m