spring.application.name=bookstore-webapp

server.port=8080
server.shutdown=graceful
spring.mvc.problemdetails.enabled=true

#api-gateway configuration
bookstore.api-gateway-url=http://localhost:8989


spring.security.oauth2.client.registration.bookstore-webapp.client-id=bookstore-webapp
spring.security.oauth2.client.registration.bookstore-webapp.client-secret=bookstore-secret
spring.security.oauth2.client.registration.bookstore-webapp.client-name=Bookstore Webapp
spring.security.oauth2.client.registration.bookstore-webapp.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.bookstore-webapp.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.bookstore-webapp.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.bookstore-webapp.scope=openid,profile,email

spring.security.oauth2.client.provider.bookstore-webapp.issuer-uri=http://localhost:9400